### ISSUE TITLE
PX4 integration suggestions

### ISSUE THREAD

**Issue by andrearlotta** [jeremyfix/ros-and-unity#1]
Hey there,
1st of all, thanks for the work you carried out, it has been really inspiring.
I wrote to you because the idea of integrating this with PX4 triggers me. I read PX4 docs, but I am struggling in finding an initial approach for the integration.
Do you have any suggestion? 
Thanks for your kind attention
Andrea

**Comment by jeremyfix** [comment]
Hello,

I fear I cannot be of any help , since I never used PX4 so far;

Best;

Jeremy.
